# Use root/example as user/password credentials
version: '3.1'

services:

  cassandra:
    image: bitnami/cassandra:latest
    restart: always
    ports:
      - 9042:9042
    environment:
      CASSANDRA_CQL_PORT_NUMBER: 9042